In [1]:
import numpy as np

In [3]:
# ! ==> Terminal

In [5]:
!pip install numpy

## Use the range command, create and print an array with the numbers: A 0-10

In [ ]:
np.arange(0, 10 + 1)

## B From 0.5 to 5 in skips of 0.25

In [81]:
np.arange(0.5, 5+0.25, 0.25)

array([0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  ,
       3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

## Use the zeros command, create and print an array of zeros in the following size:

## A: An array of 10 members in row 1

In [53]:
print(np.zeros(10, dtype=int))

[0 0 0 0 0 0 0 0 0 0]


## B:An array of 12 members in size 4 x 3

In [51]:
print(np.zeros((3, 4), dtype=float))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## 3 Use the Linspace command, create and print an array of numbers:

## a 5 organs size from 2 to 12

In [55]:
print(np.linspace(2, 12, 5, dtype=int))

[ 2  4  7  9 12]


## b Size 4 organs from 3 to 9

In [57]:
print(np.linspace(3, 9, 4, dtype=int))

[3 5 7 9]


## 4. Use the random np command, create and print an array of random numbers:

## a. 2 x 4 in size where each random number is between 0 and 0.999

In [97]:
randy = np.random.rand(2, 4)
print(randy)

[[0.98914892 0.08706298 0.31762007 0.74947255]
 [0.26359153 0.44594592 0.08807126 0.08638397]]


## b. 3 x 3 in size where each random number is integers between 10 and 20

In [87]:
randy = np.random.randint(10, 21, (3, 3))
print(randy)

[[13 19 15]
 [11 12 12]
 [13 15 14]]


## reshape to (8, 1)

In [101]:
reshaped= randy.reshape(8, 1)
print(reshaped)

[[0.98914892]
 [0.08706298]
 [0.31762007]
 [0.74947255]
 [0.26359153]
 [0.44594592]
 [0.08807126]
 [0.08638397]]


## A.What will happen if we draw random numbers using a fixed seed?

##**That the results will be repeated with each run

In [103]:
np.random.seed(42)
np.random.randint(0, 101, (2,5))

array([[51, 92, 14, 71, 60],
       [20, 82, 86, 74, 74]])

## B.The advantage of using a seed?

## 1. Reproduction of identical random results – allows repetition in code runs (e.g., in neural network training).

## 2.Comparison of results – used to check whether changes in the code affect the result or not.

## 3.Stability in simulations and statistical models.